package com.sangsok.api;
import com.fasterxml.jackson.databind.*;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;
import java.util.UUID;
import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@SpringBootTest @AutoConfigureMockMvc
class ApiFlowTests {
    @Autowired MockMvc mvc; @Autowired ObjectMapper mapper;
    private String signup(String prefix)throws Exception{String username=prefix+UUID.randomUUID().toString().substring(0,8);String body="{\"username\":\""+username+"\",\"password\":\"password123\"}";String json=mvc.perform(post("/api/auth/signup").contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().isCreated()).andReturn().getResponse().getContentAsString();return mapper.readTree(json).get("accessToken").asText();}
    private long createCase(String token,boolean certain)throws Exception{String body="{\"deceasedDisplayName\":\"테스트 고인\",\"deathDate\":\"2026-08-20\",\"awarenessDate\":\"2026-08-21\",\"awarenessDateCertain\":"+certain+",\"relationship\":\"자녀\",\"inquiryStatus\":\"RESULT_AVAILABLE\",\"minorHeirExists\":false,\"willExists\":false,\"heirCandidates\":[]}";String json=mvc.perform(post("/api/cases").header("Authorization","Bearer "+token).contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().isCreated()).andReturn().getResponse().getContentAsString();return mapper.readTree(json).get("id").asLong();}
    @Test void authenticationAndCaseOwnershipAreEnforced()throws Exception{String owner=signup("owner"),other=signup("other");long id=createCase(owner,true);mvc.perform(get("/api/cases/{id}",id)).andExpect(status().isUnauthorized());mvc.perform(get("/api/cases/{id}",id).header("Authorization","Bearer "+other)).andExpect(status().isNotFound());mvc.perform(get("/api/cases/{id}",999999).header("Authorization","Bearer "+owner)).andExpect(status().isNotFound());}
    @Test void taskCompletionActivatesNextAndCancellationMarksRecheck()throws Exception{String token=signup("task");long id=createCase(token,true);String auth="Bearer "+token;mvc.perform(post("/api/cases/{id}/roadmaps",id).header("Authorization",auth)).andExpect(status().isOk());JsonNode steps=mapper.readTree(mvc.perform(get("/api/cases/{id}/tasks",id).header("Authorization",auth)).andReturn().getResponse().getContentAsString());long first=steps.get(0).get("id").asLong(),second=steps.get(1).get("id").asLong();String done="{\"progressStatus\":\"COMPLETED\",\"resultDate\":\"2026-09-01\"}";mvc.perform(patch("/api/tasks/{id}/result",first).header("Authorization",auth).contentType(MediaType.APPLICATION_JSON).content(done)).andExpect(jsonPath("$.status").value("COMPLETED"));mvc.perform(patch("/api/tasks/{id}/result",second).header("Authorization",auth).contentType(MediaType.APPLICATION_JSON).content(done)).andExpect(jsonPath("$.status").value("COMPLETED"));mvc.perform(patch("/api/tasks/{id}/result",first).header("Authorization",auth).contentType(MediaType.APPLICATION_JSON).content("{\"progressStatus\":\"IN_PROGRESS\"}"));mvc.perform(get("/api/tasks/{id}",second).header("Authorization",auth)).andExpect(jsonPath("$.status").value("RECHECK_REQUIRED"));}
    @Test void documentCandidatesAreNotAppliedUntilConfirmAndLowConfidenceNeedsReview()throws Exception{String token=signup("doc");long id=createCase(token,true);String auth="Bearer "+token;String created=mvc.perform(post("/api/cases/{id}/documents/sample",id).header("Authorization",auth)).andReturn().getResponse().getContentAsString();long docId=mapper.readTree(created).get("id").asLong();String analyzed=mvc.perform(post("/api/documents/{id}/analyze",docId).header("Authorization",auth)).andExpect(jsonPath("$.status").value("NEEDS_REVIEW")).andReturn().getResponse().getContentAsString();mvc.perform(get("/api/cases/{id}/financial-items",id).header("Authorization",auth)).andExpect(jsonPath("$.length()").value(0));JsonNode result=mapper.readTree(analyzed).get("analysis");mvc.perform(patch("/api/documents/{id}/confirm",docId).header("Authorization",auth).contentType(MediaType.APPLICATION_JSON).content(mapper.writeValueAsString(result))).andExpect(jsonPath("$.status").value("CONFIRMED"));String itemJson=mvc.perform(get("/api/cases/{id}/financial-items",id).header("Authorization",auth)).andReturn().getResponse().getContentAsString();JsonNode list=mapper.readTree(itemJson);assertThat(list.size()).isEqualTo(2);assertThat(list.get(0).get("amountStatus").asText()).isEqualTo("NEEDS_CONFIRMATION");}
    @Test void impactfulCaseChangeMarksRoadmapDirty()throws Exception{String token=signup("edit");long id=createCase(token,true);String auth="Bearer "+token;mvc.perform(post("/api/cases/{id}/roadmaps",id).header("Authorization",auth));String body="{\"deceasedDisplayName\":\"테스트 고인\",\"deathDate\":\"2026-08-20\",\"awarenessDate\":\"2026-08-21\",\"awarenessDateCertain\":false,\"relationship\":\"자녀\",\"inquiryStatus\":\"RESULT_AVAILABLE\",\"minorHeirExists\":false,\"willExists\":false,\"heirCandidates\":[]}";mvc.perform(patch("/api/cases/{id}",id).header("Authorization",auth).contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(jsonPath("$.roadmapImpact").value(true)).andExpect(jsonPath("$.case.roadmapDirty").value(true));}
}
