create table app_user (
  id bigint generated by default as identity primary key,
  username varchar(80) not null unique,
  password_hash varchar(100) not null,
  created_at timestamp with time zone not null
);

create table inheritance_case (
  id bigint generated by default as identity primary key,
  owner_id bigint not null references app_user(id),
  deceased_display_name varchar(100) not null,
  death_date date,
  awareness_date date,
  awareness_date_certain boolean not null default false,
  relationship varchar(40) not null,
  inquiry_status varchar(40) not null,
  minor_heir_exists boolean,
  will_exists boolean,
  completed_procedures varchar(1000),
  roadmap_dirty boolean not null default false,
  roadmap_updated_at timestamp with time zone,
  created_at timestamp with time zone not null
);

create table heir_candidate (
  id bigint generated by default as identity primary key,
  case_id bigint not null references inheritance_case(id) on delete cascade,
  display_name varchar(100) not null,
  relationship varchar(40) not null,
  minor boolean not null default false
);

create table document (
  id bigint generated by default as identity primary key,
  case_id bigint not null references inheritance_case(id) on delete cascade,
  original_name varchar(255) not null,
  storage_key varchar(255) not null,
  mime_type varchar(100) not null,
  size_bytes bigint not null,
  status varchar(40) not null,
  consented_at timestamp with time zone,
  uploaded_at timestamp with time zone not null
);

create table document_analysis (
  id bigint generated by default as identity primary key,
  document_id bigint not null references document(id) on delete cascade,
  status varchar(40) not null,
  document_type varchar(80),
  result_json text,
  error_message varchar(300),
  created_at timestamp with time zone not null
);

create table financial_item (
  id bigint generated by default as identity primary key,
  case_id bigint not null references inheritance_case(id) on delete cascade,
  source_document_id bigint references document(id),
  asset_or_debt varchar(20) not null,
  item_type varchar(40) not null,
  institution varchar(160),
  amount numeric(19,2),
  amount_status varchar(30) not null,
  reference_date date,
  memo varchar(500),
  confidence numeric(5,4),
  evidence_text varchar(500),
  created_at timestamp with time zone not null
);

create table roadmap (
  id bigint generated by default as identity primary key,
  case_id bigint not null references inheritance_case(id) on delete cascade,
  version integer not null,
  active boolean not null,
  rules_version varchar(30) not null,
  created_at timestamp with time zone not null
);

create table roadmap_step (
  id bigint generated by default as identity primary key,
  roadmap_id bigint not null references roadmap(id) on delete cascade,
  step_key varchar(80) not null,
  title varchar(160) not null,
  purpose varchar(500) not null,
  sequence_no integer not null,
  status varchar(30) not null,
  deadline date,
  deadline_status varchar(30) not null,
  institution varchar(200),
  required_documents varchar(1000),
  instructions varchar(2000),
  cautions varchar(1500),
  official_url varchar(500),
  expert_recommended boolean not null default false
);

create table task_result (
  id bigint generated by default as identity primary key,
  step_id bigint not null unique references roadmap_step(id) on delete cascade,
  progress_status varchar(30) not null,
  result_date date,
  result_text varchar(500),
  memo varchar(1000),
  updated_at timestamp with time zone not null
);

create table warning (
  id bigint generated by default as identity primary key,
  case_id bigint not null references inheritance_case(id) on delete cascade,
  step_id bigint references roadmap_step(id),
  category varchar(30) not null,
  level varchar(20) not null,
  title varchar(200) not null,
  message varchar(1000) not null,
  deadline date,
  navigation_target varchar(40) not null,
  resolved boolean not null default false
);

create table chat_message (
  id bigint generated by default as identity primary key,
  case_id bigint not null references inheritance_case(id) on delete cascade,
  role varchar(20) not null,
  message varchar(2000) not null,
  intent varchar(50),
  navigation_target varchar(40),
  target_id bigint,
  created_at timestamp with time zone not null
);

create index idx_case_owner on inheritance_case(owner_id);
create index idx_document_case on document(case_id);
create index idx_financial_case on financial_item(case_id);
create index idx_roadmap_case_active on roadmap(case_id, active);
