create table refresh_token (
  id bigint generated by default as identity primary key,
  user_id bigint not null references app_user(id) on delete cascade,
  token_hash varchar(64) not null unique,
  expires_at timestamp with time zone not null,
  revoked_at timestamp with time zone,
  replaced_by_id bigint references refresh_token(id),
  created_at timestamp with time zone not null
);

create index idx_refresh_token_user on refresh_token(user_id);
